// <auto-generated />
using System;
using GFLTestTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GFLTestTask.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230920181434_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GFLTestTask.Models.Folder", b =>
                {
                    b.Property<int>("FolderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FolderID"));

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ParentFolderID")
                        .HasColumnType("int");

                    b.HasKey("FolderID");

                    b.HasIndex("ParentFolderID");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            FolderID = 1,
                            FolderName = "Creating Digital Images"
                        },
                        new
                        {
                            FolderID = 2,
                            FolderName = "Resources",
                            ParentFolderID = 1
                        },
                        new
                        {
                            FolderID = 3,
                            FolderName = "Evidence",
                            ParentFolderID = 1
                        },
                        new
                        {
                            FolderID = 4,
                            FolderName = "Graphic Products",
                            ParentFolderID = 1
                        },
                        new
                        {
                            FolderID = 5,
                            FolderName = "Primary Sources",
                            ParentFolderID = 2
                        },
                        new
                        {
                            FolderID = 6,
                            FolderName = "Secondary Sources",
                            ParentFolderID = 2
                        },
                        new
                        {
                            FolderID = 7,
                            FolderName = "Process",
                            ParentFolderID = 4
                        },
                        new
                        {
                            FolderID = 8,
                            FolderName = "Final Product",
                            ParentFolderID = 4
                        });
                });

            modelBuilder.Entity("GFLTestTask.Models.Folder", b =>
                {
                    b.HasOne("GFLTestTask.Models.Folder", "ParentFolder")
                        .WithMany("Subfolders")
                        .HasForeignKey("ParentFolderID");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("GFLTestTask.Models.Folder", b =>
                {
                    b.Navigation("Subfolders");
                });
#pragma warning restore 612, 618
        }
    }
}
